x509userproxy         = /afs/cern.ch/user/j/junghyun/ttHH_analysis/CMSSW_12_6_5/src/ttHH_CLbatch_public/proxy.cert
executable            = run_ttHtobb.sh
getenv                = True
arguments             = $(samplelist) $(ClusterId) $(ProcId)
output                = logForJob_240122_TEST/output/ttHtobb_$(ClusterId).$(ProcId).out
error                 = logForJob_240122_TEST/error/ttHtobb_$(ClusterId).$(ProcId).err
log                   = logForJob_240122_TEST/log/ttHtobb_$(ClusterId).log
should_transfer_files = IF_NEEDED
+JobFlavour = "microcentury"
queue samplelist from /afs/cern.ch/user/j/junghyun/ttHH_analysis/CMSSW_12_6_5/src/ttHH_CLbatch_public/samplelist/ttHtobb.txt
