x509userproxy         = /afs/cern.ch/user/j/junghyun/ttHH_analysis/CMSSW_12_6_5/src/ttHH_CLbatch_public/proxy.cert
executable            = run_ttZZto4b.sh
getenv                = True
arguments             = $(samplelist) $(ClusterId) $(ProcId)
output                = logForJob_231207_TEST/output/ttZZto4b_$(ClusterId).$(ProcId).out
error                 = logForJob_231207_TEST/error/ttZZto4b_$(ClusterId).$(ProcId).err
log                   = logForJob_231207_TEST/log/ttZZto4b_$(ClusterId).log
should_transfer_files = IF_NEEDED
+JobFlavour = "microcentury"
queue samplelist from /afs/cern.ch/user/j/junghyun/ttHH_analysis/CMSSW_12_6_5/src/ttHH_CLbatch_public/samplelist/ttZZto4b.txt
